### ISSUE TITLE
Issues with prompt_toolkit

### ISSUE THREAD

**Issue by foremandomai** [ctxis/cbrcli#2]
I'm using Python 2.7.13 on Debian 9.3. I installed the latest prompt_toolkit from git, and I get the error 'cannot import name style_from_dict'. 

$ python cbrcli.py
cbrcli version 1.6.4 (Selenium Green)
Traceback (most recent call last):
  File "cbrcli.py", line 24, in <module>
    from prompt_toolkit.styles import style_from_dict
ImportError: cannot import name style_from_dict

 After making that go away just to see it step forward:

$ python cbrcli.py
cbrcli version 1.6.4 (Selenium Green)
Traceback (most recent call last):
  File "cbrcli.py", line 25, in <module>
    from prompt_toolkit.token import Token

And...

~$ python cbrcli.py
cbrcli version 1.6.4 (Selenium Green)
Traceback (most recent call last):
  File "cbrcli.py", line 27, in <module>
    from prompt_toolkit.contrib.completers import WordCompleter, PathCompleter
ImportError: cannot import name WordCompleter

What is the issue?

**Comment by sevzero** [comment]
Hi,

From what you've said it sounds to me like there may be a compatibility issue with the latest version of prompt_toolkit from git.

Usually you do not need to install prompt toolkit manually as it's a dependency of cbapi. If possible I'd recommend removing the version of prompt_toolkit you installed manually and just running 'pip install cbapi' which should pull down the correct version automatically.

That said, I'm going to see if I can reproduce the issue with the git version and if so look into making it work with cbrcli.

**Comment by foremandomai** [comment]
I forgot to mention, I only installed the git version because I was having the exact same issue with the defaults via pip install cbapi. The issue persists with the latest release.

**Comment by sevzero** [comment]
It appears that the latest release of prompt_toolkit has introduced some breaking changes that are causing some of the cbrcli imports to fail. I'm going to have to take a look at exactly what has changed and handle it appropriately.

As a workaround for now you can install an older version of prompt_toolkit via pip with the command `pip install prompt_toolkit==1.0.15` and cbrcli should work.

Thanks for raising this this issue, I'm sure other people will have been encountering the same problem.

**Comment by sevzero** [comment]
I have pushed a new version of cbrcli supporting the latest version of prompt_toolkit.
