### ISSUE TITLE
Issue with Large Filemod-save

### ISSUE THREAD

**Issue by robsmallridge** [ctxis/cbrcli#3]
Hello,

Trying to do a large filemod-save and get the following error. Works on a smaller subset of the data, but as I increase the range, it starts to error.

`Traceback (most recent call last):
  File "cbrcli.py", line 1355, in <module>
    out = getattr(cbcli_cmd, '_' + cmd.replace('-', '_'), cbcli_cmd._invalid_cmd)(cmd=cmd, params=params, state=state)
  File "cbrcli.py", line 1099, in _filemods_save
    return save_extra_data(params, state, 'filemods', format_filemod_export)
  File "cbrcli.py", line 775, in save_extra_data
    for extra_data in get_extra_data(records, data_type, formatter=formatter):
  File "cbrcli.py", line 784, in get_extra_data
    for event_id, data_list in enumerate((getattr(i, 'all_' + data_type)() if getattr(i, 'all_' + data_type) else getattr(i, data_type, []) for i in records)):
  File "cbrcli.py", line 784, in <genexpr>
    for event_id, data_list in enumerate((getattr(i, 'all_' + data_type)() if getattr(i, 'all_' + data_type) else getattr(i, data_type, []) for i in records)):
AttributeError: 'NoneType' object has no attribute 'all_filemods'
`

**Comment by sevzero** [comment]
Taking a look at this now and was hoping to confirm a couple things with you to help reproduce my end.

- Can you let me know the command you're using to save the filemods?
- How many results are you attempting to export filemods for?
- Have you displayed all the results on screen before running the filemods-save command?

**Comment by robsmallridge** [comment]
I'm using the following command:

`filemods-save * /home/user/path.txt`

In total about 2,000 records, but have tried 1,000. Also displaying all results to screen before running

**Comment by sevzero** [comment]
ok great, thanks for clarifying. Originally the code limited the results it kept in memory for retrieving filemods to a list of 1000, although looking back this seems a bit arbitrary. I've pushed a new version without a limit so hopefully if you pull this version it'll work on larger result sets.

Please give it a go and let me know if it helps.

**Comment by robsmallridge** [comment]
Thanks! this now works
