### ISSUE TITLE
Unhandled exception in event loop

### ISSUE THREAD

**Issue by sumeshgopu** [ctxis/cbrcli#5]
File "C:\Users\SAMSI\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "C:\Users\SAMSI\AppData\Local\Programs\Python\Python38-32\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\SAMSI\AppData\Local\Programs\Python\Python38-32\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)

Exception [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request

**Comment by sumeshgopu** [comment]
https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1023

**Comment by sevzero** [comment]
Hi Sumesh,

Thanks for raising this. I'm struggling to reproduce the issue on my end and was hoping you could provide info on what version of Windows you are running and the versions of Python and prompt-toolkit installed? Hopefully that'll help me replicate the issue.

**Comment by sumeshgopu** [comment]
OS : Windows 10 PRO version : 10.0.18363

Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29)

**Comment by sevzero** [comment]
I still haven't been able to reproduce the issue on my setup here but have added in the fix suggested in the prompt_toolkit issue as it doesn't seem to cause any problems. Could you pull the latest version of cbrcli and let me know if it has fixed the issue for you?

**Comment by sumeshgopu** [comment]
I pulled the new version and I don't see issue now

**Comment by sevzero** [comment]
Good to hear and thanks for confirming.
